import Foundation

// MARK: - Chord

enum ChordMode: String, CaseIterable {
    case major = "M"
    case minor = "m"
}

struct Chord: Identifiable, Equatable, Hashable {
    let root: Int       // pitch class 0-11 (C=0, C#=1, ... B=11)
    let mode: ChordMode

    var id: String { "\(root)\(mode.rawValue)" }
    var rootName: String { Chord.noteNames[root] }
    var displayName: String { "\(rootName)\(mode == .minor ? "m" : "")" }

    // MIDI notes (root position, C3 = 48 base)
    var midiNotes: [UInt8] {
        let base = UInt8(48 + root)
        switch mode {
        case .major: return [base, base + 4, base + 7]
        case .minor: return [base, base + 3, base + 7]
        }
    }

    static let noteNames = ["C","C#","D","Eb","E","F","F#","G","Ab","A","Bb","B"]
}

// MARK: - NRT Operations

enum NRTOperation: String, CaseIterable {
    case L, P, R, N, H, S

    var fullName: String {
        switch self {
        case .L: return "Leading-tone Exchange"
        case .P: return "Parallel"
        case .R: return "Relative"
        case .N: return "Nebenverwandt"
        case .H: return "Hexatonic Pole"
        case .S: return "Slide"
        }
    }

    var description: String {
        switch self {
        case .L: return "Conserva la 3ra menor. Convierte la 3ra mayor en 4ta justa."
        case .P: return "Conserva la 5ta justa. Cambia el modo."
        case .R: return "Conserva la 3ra mayor. Convierte la 3ra menor en 4ta justa."
        case .N: return "Invierte la tríada alrededor de la fundamental o la 5ta."
        case .H: return "Polo hexatónico: ninguna nota en común. Equiv. a PLP."
        case .S: return "Conserva la 3ra. Desplaza la 5ta ½ tono. Equiv. a RNR."
        }
    }

    var semitonesDisplaced: Int {
        switch self {
        case .L: return 1
        case .P: return 1
        case .R: return 2
        case .N: return 2
        case .H: return 3
        case .S: return 2
        }
    }

    // Apply to a chord (all operations are involutions)
    func apply(to chord: Chord) -> Chord {
        let r = chord.root
        switch (self, chord.mode) {
        case (.L, .major): return Chord(root: (r + 4) % 12, mode: .minor)
        case (.L, .minor): return Chord(root: (r + 8) % 12, mode: .major)
        case (.P, .major): return Chord(root: r, mode: .minor)
        case (.P, .minor): return Chord(root: r, mode: .major)
        case (.R, .major): return Chord(root: (r + 9) % 12, mode: .minor)
        case (.R, .minor): return Chord(root: (r + 3) % 12, mode: .major)
        case (.N, .major): return Chord(root: (r + 5) % 12, mode: .minor)
        case (.N, .minor): return Chord(root: (r + 7) % 12, mode: .major)
        case (.H, .major): return Chord(root: (r + 8) % 12, mode: .minor)
        case (.H, .minor): return Chord(root: (r + 4) % 12, mode: .major)
        case (.S, .major): return Chord(root: (r + 1) % 12, mode: .minor)
        case (.S, .minor): return Chord(root: (r + 11) % 12, mode: .major)
        }
    }
}

// MARK: - Hexatonic Cycles
// Each cycle: 3 major + 3 minor triads, generated by alternating L and P

struct HexatonicCycle: Identifiable {
    let id: Int
    let chords: [Chord]   // 6 chords in LP order: M, m, M, m, M, m
    let name: String

    // The 4 hexatonic cycles, seeded from major chords on C, C#, D, Eb
    static let all: [HexatonicCycle] = (0..<4).map { idx in
        var chords: [Chord] = []
        var current = Chord(root: idx, mode: .major)
        for i in 0..<6 {
            chords.append(current)
            current = (i % 2 == 0)
                ? NRTOperation.L.apply(to: current)
                : NRTOperation.P.apply(to: current)
        }
        let keys = ["cycle.hex.n", "cycle.hex.ne", "cycle.hex.e", "cycle.hex.s"]
        let names = keys.map { NSLocalizedString($0, comment: "") }
        return HexatonicCycle(id: idx, chords: chords, name: names[idx])
    }

    func contains(_ chord: Chord) -> Bool { chords.contains(chord) }
}

// MARK: - Weitzmann Regions
// Each region: 3 major + 3 minor triads related to an augmented triad
// Aug chord {r, r+4, r+8}:
//   Major chords: roots r, r+4, r+8 (move aug note DOWN ½ to get major triad)
//   Minor chords: roots r+1, r+5, r+9 (move aug note UP ½ to get minor triad)

struct WeitzmannRegion: Identifiable {
    let id: Int
    let chords: [Chord]
    let augRoot: Int    // pitch class of augmented triad (root = lowest aug note)
    let name: String

    static let all: [WeitzmannRegion] = (0..<4).map { idx in
        let augRoot = idx   // 0=C aug, 1=Db aug, 2=D aug, 3=Eb aug
        var chords: [Chord] = []
        for step in 0..<3 {
            let pc = (augRoot + step * 4) % 12
            chords.append(Chord(root: pc, mode: .major))          // roots: r, r+4, r+8
            chords.append(Chord(root: (pc + 1) % 12, mode: .minor)) // roots: r+1, r+5, r+9
        }
        let names = ["Weitzmann C+", "Weitzmann Db+", "Weitzmann D+", "Weitzmann Eb+"]
        return WeitzmannRegion(id: idx, chords: chords, augRoot: augRoot, name: names[idx])
    }

    func contains(_ chord: Chord) -> Bool { chords.contains(chord) }
}

// MARK: - Cube Dance

// Layout: 28 nodes in a ring.
// Aug nodes at ring positions 0, 7, 14, 21.
// Each hexatonic cycle fills 6 positions between two aug nodes.
//
// Ring order:
//   pos 0:  Aug(C=0)
//   pos 1-6: Hexatonic cycle 0 → [CM, Em, EM, Abm, AbM, Cm]
//   pos 7:  Aug(Db=1)
//   pos 8-13: Hexatonic cycle 1 → [C#M, Fm, FM, Am, AM, C#m]
//   pos 14: Aug(D=2)
//   pos 15-20: Hexatonic cycle 2 → [DM, F#m, F#M, Bbm, BbM, Dm]
//   pos 21: Aug(Eb=3)
//   pos 22-27: Hexatonic cycle 3 → [EbM, Gm, GM, Bm, BM, Ebm]

struct CubeDanceNode: Identifiable, Equatable {
    let chord: Chord?       // nil = augmented node
    let augRoot: Int?       // pitch class for augmented nodes
    let ringPosition: Int   // 0-27

    var id: String {
        if let c = chord { return c.id }
        return "aug\(augRoot ?? 0)"
    }

    var displayName: String {
        if let c = chord { return c.displayName }
        return "\(Chord.noteNames[augRoot ?? 0])+"
    }

    var isAugmented: Bool { chord == nil }
}

struct CubeDanceEdge: Identifiable {
    let id: String
    let fromId: String
    let toId: String
    let solid: Bool   // true = hexatonic (solid), false = Weitzmann (dashed)
}

struct CubeDance {
    let nodes: [CubeDanceNode]
    let edges: [CubeDanceEdge]

    static let shared = CubeDance()

    init() {
        var ns: [CubeDanceNode] = []

        // Aug nodes
        for (i, augRoot) in [0, 1, 2, 3].enumerated() {
            ns.append(CubeDanceNode(chord: nil, augRoot: augRoot, ringPosition: i * 7))
        }

        // Triad nodes from hexatonic cycles
        for (cycleIdx, cycle) in HexatonicCycle.all.enumerated() {
            let basePos = cycleIdx * 7 + 1
            for (i, chord) in cycle.chords.enumerated() {
                ns.append(CubeDanceNode(chord: chord, augRoot: nil, ringPosition: basePos + i))
            }
        }

        let nodeById = Dictionary(uniqueKeysWithValues: ns.map { ($0.id, $0) })
        var es: [CubeDanceEdge] = []

        // Solid edges: consecutive pairs within each hexatonic cycle
        for cycle in HexatonicCycle.all {
            for i in 0..<cycle.chords.count {
                let a = cycle.chords[i]
                let b = cycle.chords[(i + 1) % cycle.chords.count]
                let eid = "\(a.id)-\(b.id)"
                if nodeById[a.id] != nil && nodeById[b.id] != nil {
                    es.append(CubeDanceEdge(id: eid, fromId: a.id, toId: b.id, solid: true))
                }
            }
        }

        // Dashed edges: aug nodes → Weitzmann region triads
        for region in WeitzmannRegion.all {
            let augId = "aug\(region.augRoot)"
            for chord in region.chords {
                if nodeById[chord.id] != nil {
                    let eid = "\(augId)-\(chord.id)"
                    es.append(CubeDanceEdge(id: eid, fromId: augId, toId: chord.id, solid: false))
                }
            }
        }

        self.nodes = ns
        self.edges = es
    }

    func node(for chord: Chord) -> CubeDanceNode? {
        nodes.first { $0.chord == chord }
    }
}
